### PR TITLE
SPONSORSHIP_OFFER

### PR DESCRIPTION
**Pull request by lgarron**
dear maintainers,

i would like to extend an exclusive 30-day sponsorship offer for your excellent online experience
for the generous price of 5 mBTC, i would like 2 emblazon my 1337 hacker handle on your adspace

plz let me know if this is acceptable and I can send payment immediately

### CODE REVIEW

**Comment by diracdeltas** [comment]
Thank you for the offer. I will pass this on to Finance and they'll move forward from there.

**Comment by diracdeltas** [comment]
Finance says we would be happy to run this ad for 30 days for the low, low price of 5 mBTC

**Comment by lgarron** [comment]
Excellent! plz send payment address

**Comment by diracdeltas** [comment]
> Excellent! plz send payment address

1NjwoEtmgkqRcXhjGyVHGBbGJXnDsdnvi1

**Comment by diracdeltas** [comment]
received. going to make a staging brach and merge this

**Comment by diracdeltas** [comment]
cherry-picked!

**Pull request closed without merging**
